/** Same-origin management UI for the authenticated Control Plane. */
export function renderControlPlaneConsole(): string {
  return String.raw`<!doctype html>
<html lang="zh-CN">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="color-scheme" content="dark" />
  <title>SPINAL-PLUG // Neural Memory Control</title>
  <link rel="preconnect" href="https://fonts.googleapis.com" />
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
  <link href="https://fonts.googleapis.com/css2?family=DM+Mono:wght@400;500&family=Fraunces:opsz,wght@9..144,600;9..144,700&family=Noto+Sans+SC:wght@400;500;600;700&display=swap" rel="stylesheet" />
  <style>
    :root { --ink:#120b0a; --panel:#211514; --panel-2:#2e1d1a; --line:#5a3932; --paper:#f5e7d3; --muted:#c0aaa0; --red:#ff4d38; --lime:#c6ef6a; --blue:#67d6df; --yellow:#ffd166; --mono:"DM Mono",monospace; --display:"Fraunces","Noto Sans SC",serif; --sans:"Noto Sans SC",sans-serif; }
    * { box-sizing:border-box; } body { margin:0; min-height:100vh; color:var(--paper); background:radial-gradient(circle at 82% -5%,#5b201b 0,transparent 31rem),radial-gradient(circle at 8% 105%,#1f4848 0,transparent 28rem),linear-gradient(135deg,#140c0b,#1e1211 55%,#100b0a); font-family:var(--sans); }
    button,input { font:inherit; } button { cursor:pointer; } .shell { width:min(1480px,calc(100% - 36px)); margin:0 auto; padding:20px 0 44px; }
    header { display:flex; gap:20px; align-items:center; justify-content:space-between; padding:0 0 18px; border-bottom:1px solid var(--line); } .brand { display:flex; align-items:center; gap:12px; } .mark { width:27px; height:27px; border:3px solid var(--red); border-radius:50%; position:relative; } .mark:after { content:""; position:absolute; width:9px; height:9px; border-radius:50%; background:var(--blue); right:-7px; bottom:-6px; } h1 { margin:0; font:700 23px/1 var(--display); letter-spacing:-.04em; } .sub { margin-top:5px; color:var(--muted); font:11px/1.4 var(--mono); letter-spacing:.06em; }
    .status { display:flex; align-items:center; gap:8px; color:var(--muted); font:11px/1 var(--mono); } .dot { width:8px; height:8px; border-radius:50%; background:var(--yellow); box-shadow:0 0 0 4px rgba(247,201,93,.12); } .dot.ok { background:var(--lime); box-shadow:0 0 0 4px rgba(187,239,89,.12); }
    .auth { display:grid; grid-template-columns:1fr auto; gap:10px; margin:20px 0; padding:14px; background:rgba(27,32,24,.86); border:1px solid var(--line); } .auth label { color:var(--muted); font:11px/1.5 var(--mono); } .auth input { width:100%; margin-top:5px; color:var(--paper); padding:10px 11px; border:1px solid #56644d; background:#121510; outline:none; } .auth input:focus { border-color:var(--lime); } .action { align-self:end; padding:11px 14px; border:1px solid var(--lime); color:var(--ink); background:var(--lime); font:500 11px/1 var(--mono); } .action:hover { box-shadow:3px 3px 0 var(--red); transform:translate(-1px,-1px); }
    .layout { display:grid; grid-template-columns:275px minmax(0,1fr); gap:18px; } aside,.card { border:1px solid var(--line); background:rgba(27,32,24,.82); } aside { min-height:690px; } .aside-head,.card-head { display:flex; align-items:center; justify-content:space-between; padding:13px 14px; border-bottom:1px solid var(--line); color:var(--muted); font:500 10px/1 var(--mono); letter-spacing:.1em; text-transform:uppercase; }
    .space-list,.device-list { padding:8px; } .space { width:100%; text-align:left; color:var(--paper); padding:12px; border:1px solid transparent; background:transparent; } .space:hover,.space.active { border-color:#59674e; background:#252d20; } .space strong { display:block; font:600 14px/1.3 var(--sans); } .space span { display:block; margin-top:5px; color:var(--muted); font:10px/1.3 var(--mono); overflow:hidden; text-overflow:ellipsis; white-space:nowrap; } .section-label { padding:16px 14px 4px; color:var(--lime); font:500 10px/1 var(--mono); letter-spacing:.1em; }
    .device { padding:10px 12px; border-top:1px solid rgba(58,68,51,.65); } .device strong { display:block; font:500 12px/1.3 var(--sans); } .device small { display:block; margin-top:4px; color:var(--muted); font:10px/1.4 var(--mono); }
    main { min-width:0; } .empty { display:grid; min-height:500px; place-items:center; padding:35px; text-align:center; color:var(--muted); border:1px dashed var(--line); font:14px/1.8 var(--sans); } .empty b { display:block; margin-bottom:8px; color:var(--paper); font:600 26px/1.2 var(--display); }
    .space-title { display:flex; align-items:end; justify-content:space-between; gap:20px; margin:6px 0 18px; } .space-title h2 { margin:0; font:700 clamp(30px,4vw,48px)/1 var(--display); letter-spacing:-.05em; } .space-title p { margin:7px 0 0; color:var(--muted); font:11px/1.5 var(--mono); } .refresh { padding:8px 10px; border:1px solid #66775a; color:var(--paper); background:transparent; font:500 10px/1 var(--mono); }
    .stats { display:grid; grid-template-columns:repeat(5,1fr); gap:10px; margin-bottom:18px; } .stat { min-height:112px; padding:14px; border:1px solid var(--line); background:linear-gradient(145deg,rgba(43,52,37,.94),rgba(26,31,23,.95)); } .stat span { color:var(--muted); font:10px/1.3 var(--mono); text-transform:uppercase; letter-spacing:.08em; } .stat b { display:block; margin-top:18px; font:700 36px/1 var(--display); letter-spacing:-.05em; } .stat.candidate b{color:var(--yellow)} .stat.dispute b{color:var(--red)} .stat.checkpoint b{color:var(--blue)}
    .grid { display:grid; grid-template-columns:1.03fr .97fr; gap:18px; } .card { min-width:0; overflow:hidden; } .card-body { padding:14px; } .memory { padding:12px 0; border-bottom:1px solid rgba(58,68,51,.75); } .memory:last-child { border-bottom:0; } .memory-top { display:flex; align-items:center; justify-content:space-between; gap:8px; } .memory strong { font:600 13px/1.45 var(--sans); } .memory p { margin:7px 0 0; color:#cbd2c5; font-size:12px; line-height:1.7; } .tag { flex:0 0 auto; padding:4px 6px; border:1px solid #607055; color:var(--lime); font:10px/1 var(--mono); text-transform:uppercase; } .tag.candidate{color:var(--yellow);border-color:#806b32}.tag.disputed{color:var(--red);border-color:#8b463a}.tag.deleted{color:#9b9b92;border-color:#57574f}.meta { margin-top:8px; color:var(--muted); font:9px/1.45 var(--mono); }
    .handoff { padding:13px; border-left:3px solid var(--blue); background:rgba(107,183,255,.06); } .handoff h3 { margin:0; font:600 15px/1.4 var(--sans); } .handoff p,.handoff li { color:#cbd2c5; font-size:12px; line-height:1.6; } .handoff ul { margin:8px 0 0; padding-left:17px; } .timeline { max-height:530px; overflow:auto; padding:3px 14px 14px; } .event { display:grid; grid-template-columns:10px 1fr; gap:11px; padding:12px 0; border-bottom:1px solid rgba(58,68,51,.72); } .event i { width:8px; height:8px; margin-top:5px; border-radius:50%; background:var(--blue); box-shadow:0 0 0 3px rgba(107,183,255,.1); } .event.memory-candidate-created i{background:var(--yellow)} .event.memory-deleted i{background:var(--red)} .event.checkpoint-created i{background:var(--lime)} .event strong { font:500 11px/1.4 var(--mono); } .event p { margin:4px 0 0; color:var(--muted); font:11px/1.55 var(--sans); } .event small { color:#788371; font:9px/1.5 var(--mono); }
    .error { margin:16px 0; padding:11px 13px; color:#ffb1a4; border:1px solid #743e35; background:rgba(116,62,53,.22); font:11px/1.5 var(--mono); } .hidden { display:none!important; }
    @media(max-width:980px){ .layout{grid-template-columns:1fr} aside{min-height:auto}.stats{grid-template-columns:repeat(3,1fr)}.grid{grid-template-columns:1fr} } @media(max-width:590px){ .shell{width:min(100% - 22px,760px)}header{align-items:flex-start}.auth{grid-template-columns:1fr}.stats{grid-template-columns:repeat(2,1fr)}.space-title{align-items:flex-start;flex-direction:column} }
  </style>
</head>
<body>
<div class="shell">
  <header><div class="brand"><span class="mark"></span><div><h1>SPINAL-PLUG</h1><div class="sub">NEURAL MEMORY CONTROL / LINK GOVERNANCE</div></div></div><div class="status"><i id="status-dot" class="dot"></i><span id="status-text">AWAITING SPINAL LINK</span></div></header>
  <form id="auth-form" class="auth"><label>脊椎栓设备令牌<input id="token" type="password" autocomplete="off" placeholder="mpd_..." /></label><button id="connect" type="submit" class="action">锁定神经链路</button></form>
  <div id="error" class="error hidden"></div>
  <section class="layout"><aside><div class="aside-head"><span>Memory Chambers</span><span id="space-count">0</span></div><div id="spaces" class="space-list"></div><div class="section-label">Linked Incarnations</div><div id="devices" class="device-list"></div></aside><main id="main"><div class="empty"><div><b>脊椎栓未锁定</b>输入设备令牌后，建立神经链路并查看项目记忆、候选、冲突、删除记录与工作交接。</div></div></main></section>
</div>
<script>
  const state={token:localStorage.getItem("spinal-plug.console.token")||localStorage.getItem("spinal-plug.console.token")||"",spaces:[],devices:[],spaceId:null};
  const $=id=>document.getElementById(id); $("token").value=state.token;
  const esc=value=>String(value??"").replace(/[&<>\"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;"}[c]));
  const setStatus=(text,ok=false)=>{ $("status-text").textContent=text; $("status-dot").classList.toggle("ok",ok); };
  const problem=message=>{ $("error").textContent=message; $("error").classList.remove("hidden"); };
  const clearProblem=()=>$("error").classList.add("hidden");
  async function api(path){ const response=await fetch(path,{headers:{authorization:"Bearer "+state.token}}); const body=await response.json(); if(!response.ok) throw new Error(body.error||("HTTP "+response.status)); return body; }
  function renderSidebar(){ $("space-count").textContent=state.spaces.length; $("spaces").innerHTML=state.spaces.map(space=>'<button class="space '+(space.spaceId===state.spaceId?'active':'')+'" data-space="'+esc(space.spaceId)+'"><strong>'+esc(space.displayName)+'</strong><span>'+esc(space.type)+' / '+esc(space.role)+' / '+esc(space.spaceId)+'</span></button>').join("")||'<div class="meta">暂无可访问的 Project Space</div>'; $("devices").innerHTML=state.devices.map(device=>'<div class="device"><strong>'+esc(device.displayName)+'</strong><small>'+esc(device.status)+' · '+esc(device.deviceId)+'</small></div>').join("")||'<div class="meta">暂无设备</div>'; document.querySelectorAll("[data-space]").forEach(node=>node.addEventListener("click",()=>{state.spaceId=node.dataset.space;renderSidebar();loadSpace();})); }
  function memoryRow(memory){ const tag=memory.status==='candidate'?'candidate':memory.status==='disputed'?'disputed':memory.status==='deleted'?'deleted':''; return '<article class="memory"><div class="memory-top"><strong>'+esc(memory.title)+'</strong><span class="tag '+tag+'">'+esc(memory.status)+'</span></div><p>'+esc(memory.statement)+'</p><div class="meta">'+esc(memory.kind)+' · '+esc(memory.origin||"unknown")+' · confidence '+esc(memory.confidence??"-")+' · '+esc(memory.updatedAt)+'</div></article>'; }
  function eventSummary(event){ if(event.eventType.startsWith("checkpoint.")){ const checkpoint=event.payload?.checkpoint||{}; return esc(checkpoint.title||event.eventType); } const payload=event.payload||{}; return esc(payload.title||payload.statement||event.eventType); }
  function renderSpace(snapshot,events){ const active=snapshot.memories||[], candidates=snapshot.candidates||[], disputes=snapshot.disputes||[], deleted=snapshot.deleted||[], checkpoints=snapshot.checkpoints||[]; const space=state.spaces.find(item=>item.spaceId===state.spaceId)||{}; const list=(title,items,empty)=>'<section class="card"><div class="card-head"><span>'+title+'</span><span>'+items.length+'</span></div><div class="card-body">'+(items.length?items.map(memoryRow).join(""):'<div class="meta">'+empty+'</div>')+'</div></section>'; const handoffs=checkpoints.length?checkpoints.map(checkpoint=>'<article class="handoff"><h3>'+esc(checkpoint.title)+'</h3>'+(checkpoint.summary?'<p>'+esc(checkpoint.summary)+'</p>':'')+(checkpoint.openTasks?.length?'<p><b>待办</b></p><ul>'+checkpoint.openTasks.map(task=>'<li>'+esc(task)+'</li>').join("")+'</ul>':'')+(checkpoint.blockers?.length?'<p><b>阻塞</b> '+esc(checkpoint.blockers.join("；"))+'</p>':'')+(checkpoint.nextAction?'<p><b>下一步</b> '+esc(checkpoint.nextAction)+'</p>':'')+'<div class="meta">'+esc(checkpoint.updatedAt)+' · '+esc(checkpoint.branchId||"default")+'</div></article>').join(""):'<div class="meta">没有已同步的工作交接包。</div>'; $("main").innerHTML='<div class="space-title"><div><h2>'+esc(space.displayName)+'</h2><p>'+esc(space.type)+' · '+esc(space.repository?.canonicalRemote||space.spaceId)+' · neural snapshot '+esc(snapshot.cursor)+'</p></div><button id="refresh" class="refresh">刷新链路</button></div><section class="stats"><div class="stat"><span>Memory Fidelity</span><b>'+active.length+'</b></div><div class="stat candidate"><span>Unverified Signals</span><b>'+candidates.length+'</b></div><div class="stat dispute"><span>Signal Conflicts</span><b>'+disputes.length+'</b></div><div class="stat checkpoint"><span>Handoff Packets</span><b>'+checkpoints.length+'</b></div><div class="stat"><span>Purged Records</span><b>'+deleted.length+'</b></div></section><section class="grid"><div class="stack">'+list("Verified memory blocks",active,"暂无已验证记忆块。")+'<div style="height:18px"></div>'+list("Unverified neural signals",candidates,"没有待审信号。")+'<div style="height:18px"></div>'+list("Link conflicts",(snapshot.disputed||[]),"没有未解决链路冲突。")+'</div><div class="stack"><section class="card"><div class="card-head"><span>Latest handoff packets</span><span>'+checkpoints.length+'</span></div><div class="card-body">'+handoffs+'</div></section><div style="height:18px"></div><section class="card"><div class="card-head"><span>Neural event timeline</span><span>'+events.length+'</span></div><div class="timeline">'+events.map(event=>'<article class="event '+esc(event.eventType.replaceAll(".","-"))+'"><i></i><div><strong>'+esc(event.eventType)+'</strong><p>'+eventSummary(event)+'</p><small>'+esc(event.createdAt)+' · '+esc(event.actor?.host||"unknown")+' / '+esc(event.actor?.deviceId||"unknown")+'</small></div></article>').join("")+'</div></section></div></section>'; $("refresh").addEventListener("click",loadSpace); }
  async function loadSpace(){ if(!state.spaceId)return; try{ clearProblem(); const [snapshot,timeline]=await Promise.all([api('/v1/spaces/'+encodeURIComponent(state.spaceId)+'/snapshot'),api('/v1/spaces/'+encodeURIComponent(state.spaceId)+'/events?limit=100')]); renderSpace(snapshot,timeline.events); setStatus("NEURAL LINK LOCKED",true); }catch(error){problem(error.message);setStatus("LINK INTERRUPTION",false);} }
  async function connect(){ try{ state.token=$("token").value.trim(); if(!state.token)throw new Error("请输入脊椎栓设备令牌。"); localStorage.setItem("spinal-plug.console.token",state.token); clearProblem(); setStatus("LOCKING SPINAL PLUG",false); const [spaceResult,deviceResult]=await Promise.all([api('/v1/spaces'),api('/v1/devices')]); state.spaces=spaceResult.spaces||[];state.devices=deviceResult.devices||[];state.spaceId=state.spaces.find(space=>space.spaceId===state.spaceId)?.spaceId||state.spaces[0]?.spaceId||null;renderSidebar(); if(state.spaceId)await loadSpace();else setStatus("NO MEMORY CHAMBER ACCESS",true); }catch(error){problem(error.message);setStatus("AUTHENTICATION FAILED",false);} }
  $("auth-form").addEventListener("submit",event=>{event.preventDefault();connect();}); if(state.token)connect();
</script>
</body></html>`;
}
